# >>> AUTO-GEN BEGIN: Pre-commit Hooks v1.0
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
