# >>> AUTO-GEN BEGIN: pre-commit config v1.0
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: validate-fences
        name: validate-fences
        entry: python scripts/validators/validate_fences.py
        language: system
        files: '(^generated/|^registry/|^docs/|^\.github/)'
      - id: validate-registry
        name: validate-registry
        entry: python scripts/validators/validate_registry.py
        language: system
        files: '^registry/'
# >>> AUTO-GEN END: pre-commit config v1.0
