services:
  api:
    build:
      context: .
    image: astroengine:latest
    command:
      - serve-api
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      DATABASE_URL: ${DATABASE_URL:-sqlite+pysqlite:////data/dev.db}
      SE_EPHE_PATH: /opt/ephe
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    ports:
      - "8000:8000"
    volumes:
      - ./data/ephe:/opt/ephe
      - ./data:/data

  ui:
    image: astroengine:latest
    command:
      - serve-ui
      - --server.address
      - 0.0.0.0
      - --server.port
      - "8501"
    depends_on:
      api:
        condition: service_healthy
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      API_BASE_URL: ${API_BASE_URL:-http://api:8000}
      DATABASE_URL: ${DATABASE_URL:-sqlite+pysqlite:////data/dev.db}
      SE_EPHE_PATH: /opt/ephe
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://api:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "8501:8501"
    volumes:
      - ./data/ephe:/opt/ephe
      - ./data:/data

  tools:
    profiles:
      - tools
    image: astroengine:latest
    entrypoint:
      - /bin/sh
      - -c
    command:
      - sleep infinity
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      DATABASE_URL: ${DATABASE_URL:-sqlite+pysqlite:////data/dev.db}
      SE_EPHE_PATH: /opt/ephe
    volumes:
      - ./data/ephe:/opt/ephe
      - ./data:/data
