services:
  api:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      DATABASE_URL: ${DATABASE_URL:-sqlite+pysqlite:////workspace/data/dev.db}
      SE_EPHE_PATH: /opt/ephe
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
      - ./data/ephe:/opt/ephe
    working_dir: /workspace

  ui:
    build:
      context: .
    command: streamlit run ui/streamlit/altaz_app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - api
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      API_BASE_URL: ${API_BASE_URL:-http://api:8000}
      SE_EPHE_PATH: /opt/ephe
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
      - ./data/ephe:/opt/ephe
    working_dir: /workspace

  tools:
    profiles:
      - tools
    build:
      context: .
    command: sleep infinity
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      SE_EPHE_PATH: /opt/ephe
    volumes:
      - .:/workspace
      - ./data/ephe:/opt/ephe
    working_dir: /workspace
