version: "3.9"
services:
  api:
    build: .
    image: astroengine:api
    environment:
      DB_URL: ${DB_URL:-sqlite:///./dev.db}
      ASTROENGINE_HOME: /data/.astroengine
      SE_EPHE_PATH: ${SE_EPHE_PATH:-}
      AE_QCACHE_SIZE: ${AE_QCACHE_SIZE:-8192}
      AE_QCACHE_SEC: ${AE_QCACHE_SEC:-0.5}
    volumes:
      - ./:/app
      - ./data:/data
    ports:
      - "8000:8000"
    command: ["uvicorn","${APP_MODULE:-app.main:app}","--host","0.0.0.0","--port","8000","--workers","4"]

  ui:
    build: .
    image: astroengine:ui
    environment:
      ASTROENGINE_HOME: /data/.astroengine
      SE_EPHE_PATH: ${SE_EPHE_PATH:-}
    volumes:
      - ./:/app
      - ./data:/data
    ports:
      - "8501:8501"
    command: ["streamlit","run","${UI_ENTRY:-ui/streamlit/vedic_app.py}"]
