# >>> AUTO-GEN BEGIN: AstroEngine Conda Env v1.1
name: astroengine
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - pip:
      - -e .
      - .[dev]
      - .[api]
      - .[charts]
      - .[locational]
      - .[fallback-ephemeris]
      - .[astro-core]
      - .[catalogs]
      - .[tz]
      - .[qa-novas]
      - .[trad]
# >>> AUTO-GEN END: AstroEngine Conda Env v1.1
