# >>> AUTO-GEN BEGIN: AstroEngine Conda Env v1.0
name: astroengine
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - pip:
      - -e .
      - .[api]
      - .[charts]
      - .[locational]
      - .[fallback-ephemeris]
      - .[dev]
# >>> AUTO-GEN END: AstroEngine Conda Env v1.0
