# >>> AUTO-GEN BEGIN: packaging config v1.0
[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.0.0"
description = "AstroEngine — generated-first transit engine"
authors = [{ name = "AstroEngine" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pyyaml>=6.0.2",
]

[tool.setuptools]
package-dir = {"" = "generated"}

[tool.setuptools.packages.find]
where = ["generated"]
include = ["astroengine*"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B"]
# >>> AUTO-GEN END: packaging config v1.0
