# >>> AUTO-GEN BEGIN: packaging config v1.1
[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.0.0"
description = "AstroEngine — generated-first transit engine"
authors = [{ name = "AstroEngine" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pyyaml>=6.0.2",
]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["astroengine*"]
exclude = ["generated*"]
# >>> AUTO-GEN END: packaging config v1.1

# >>> AUTO-GEN BEGIN: ruff target py311 v1.1
[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B"]
target-version = "py311"
# >>> AUTO-GEN END: ruff target py311 v1.1
