[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.2.0"
description = "Astrology engine runtimes and schema contracts"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = {text = "Proprietary"}
authors = [
  {name = "AstroEngine Maintainers"}
]
dependencies = [

]

[project.optional-dependencies]
cli = [
  "click>=8.1",
  "rich>=13",
]
data = [
  "numpy>=1.26",
  "pandas>=2.0",
  "scipy>=1.11",
]
time = [
  "python-dateutil>=2.8",
  "pytz>=2023.3",
]
dev = [

]

[tool.setuptools.packages.find]
where = ["."]
include = ["astroengine*"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.black]
target-version = ["py311"]
line-length = 100

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["astroengine"]

[tool.mypy]
python_version = "3.11"
strict = true
files = ["astroengine/core", "astroengine/ephemeris", "astroengine/chart"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["astroengine.modules.*"]
ignore_errors = true
