[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.1.0"
description = "Modular astrology computation engine with gating, timelords, directions, and synastry pipelines."
authors = [{name = "AstroEngine Team"}]
dependencies = [
    "pandas>=2.0",
    "numpy>=1.24",
    "pyarrow>=10.0",
    "pyyaml>=6.0",
]
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
