[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.2.0"
description = "Astrology engine runtimes and schema contracts"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = {text = "Proprietary"}
authors = [
  {name = "AstroEngine Maintainers"}
]
dependencies = [
  "numpy>=1.26,<2.0",
  "pandas>=2.2,<2.3",
  "scipy>=1.13,<1.14",
  "pyswisseph>=2.10.3,<2.11",
  "python-dateutil>=2.9",
  "pytz>=2024.1",
  "click>=8.1",
  "rich>=13.7",
  "PyYAML>=6.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.2",
  "black>=24.4",
  "ruff>=0.5",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["astroengine*"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.black]
target-version = ["py311"]
line-length = 100

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["astroengine"]
