# >>> AUTO-GEN BEGIN: AstroEngine Dependencies v1.1
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astroengine"
version = "0.1.0"
description = "AstroEngine — modular transit engine and astrology toolkit"
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "AstroEngine Team" }]

# Core runtime deps (minimal engine run)
dependencies = [
  "pyswisseph>=2.10.4",      # Swiss Ephemeris bindings
  "numpy>=1.26",
  "pandas>=2.2",
  "pyarrow>=16.0",           # Parquet/Arrow IO
  "python-dateutil>=2.9",
  "tzdata>=2024.1",
  "PyYAML>=6.0",
  "pluggy>=1.5",
  "click>=8.1",
  "rich>=13.7"
]

[project.optional-dependencies]
api = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30"
]
charts = [
  "matplotlib>=3.8"
]
locational = [
  "pyproj>=3.6",
  "shapely>=2.0",
  "geographiclib>=2.0"
]
# New extras — install on-demand only
fallback-ephemeris = [
  "skyfield>=1.49",
  "jplephem>=2.21"
]
astro-core = [
  "astropy>=6.0"
]
catalogs = [
  "astroquery>=0.4.7"
]
tz = [
  "timezonefinder[numba]>=6.5"
]
qa-novas = [
  "novas>=3.1.1"
]
trad = [
  "flatlib>=0.2"
]
dev = [
  "pytest>=8.2",
  "pytest-cov>=5.0",
  "hypothesis>=6.112",
  "ruff>=0.6.5",
  "black>=24.8",
  "isort>=5.13"
]

[tool.setuptools]
packages = { find = { where = ["."], exclude = ["tests", "docs", "scripts"] } }

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "C4", "ICN"]

[tool.black]
line-length = 100
# >>> AUTO-GEN END: AstroEngine Dependencies v1.1
