line-length = 100
target-version = "py311"
extend-exclude = [
    "apps",
    "datasets",
    "db",
    "generated",
    "profiles",
    "registry",
    "rulesets",
    "scripts",
    ".github",
    "astroengine/modules",
    "astroengine/mundane",
    "astroengine/narrative",
]

[lint]
select = ["E", "F", "I", "UP", "B"]
