apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astroengine-viewer
rules:
  - apiGroups: ["", "batch", "extensions"]
    resources: ["pods", "services", "deployments", "jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astroengine-analyst
rules:
  - apiGroups: ["apps", "batch"]
    resources: ["deployments", "jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astroengine-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
