apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astroengine-workers.fullname" . }}
  labels:
    {{- include "astroengine-workers.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "astroengine-workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "astroengine-workers.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.queue.brokerUrlSecret }}
                  key: url
            - name: RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.queue.resultBackendSecret }}
                  key: url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
