"""AstroEngine package bootstrap and public surface exports."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .astro import declination  # ENSURE-LINE
from .canonical import (
    BodyPosition,  # ENSURE-LINE
    TransitEvent,  # ENSURE-LINE
)
from .catalogs import (
    VCA_CENTAURS,
    VCA_CORE_BODIES,
    VCA_EXT_ASTEROIDS,
    VCA_SENSITIVE_POINTS,
    VCA_TNOS,
    sbdb,  # ENSURE-LINE
)
from .chart import (
    ChartLocation,
    CompositePosition,
    DirectedChart,
    HarmonicChart,
    HarmonicPosition,
    MidpointCompositeChart,
    NatalChart,
    ProgressedChart,
    ReturnChart,
    compute_composite_chart,
    compute_harmonic_chart,
    compute_natal_chart,
    compute_return_chart,
    compute_secondary_progressed_chart,
    compute_solar_arc_chart,
)
from .chart.config import ChartConfig
from .core import (  # noqa: F401
    DOMAINS,
    ELEMENTS,
    ZODIAC_ELEMENT_MAP,
    AngleTracker,
    DomainResolution,
    DomainResolver,
    TransitEngine,  # ENSURE-LINE
    TransitEngineConfig,
    TransitEvent,  # ENSURE-LINE
    TransitScanConfig,  # ENSURE-LINE
    apply_profile_if_any,
    classify_relative_motion,
    compute_domain_factor,
    get_active_aspect_angles,
    get_feature_flag,
    load_profile_json,
    maybe_attach_domain_fields,
    natal_domain_factor,
    normalize_degrees,
    profile_into_ctx,
    to_tt,
)
from .diagnostics import collect_diagnostics  # ENSURE-LINE
from .ephemeris import (  # noqa: F401
    EphemerisAdapter,
    EphemerisConfig,
    EphemerisSample,
    ObserverLocation,
    RefinementBracket,
    RefinementError,
    SwissEphemerisAdapter,
    TimeScaleContext,
    refine_event,
)
from .esoteric import (
    ALCHEMY_STAGES,
    DECANS,
    ELDER_FUTHARK_RUNES,
    GOLDEN_DAWN_GRADES,
    I_CHING_HEXAGRAMS,
    MASTER_NUMBERS,
    NUMEROLOGY_NUMBERS,
    SEVEN_RAYS,
    TAROT_COURTS,
    TAROT_MAJORS,
    TAROT_SPREADS,
    TREE_OF_LIFE_PATHS,
    TREE_OF_LIFE_SEPHIROTH,
    AlchemyStage,
    DecanAssignment,
    DecanDefinition,
    GoldenDawnGrade,
    Hexagram,
    NumerologyNumber,
    PathDefinition,
    RayDefinition,
    Rune,
    SephiraDefinition,
    TarotCourtCard,
    TarotMajorArcana,
    TarotSpread,
    assign_decans,
    decan_for_longitude,
)

try:
    from .events import (
        DirectionEvent,
        EclipseEvent,
        LunationEvent,
        OutOfBoundsEvent,
        ProfectionEvent,
        ProgressionEvent,
        ReturnEvent,
        StationEvent,
    )
except ImportError:  # pragma: no cover - optional legacy surface
    LunationEvent = EclipseEvent = StationEvent = ReturnEvent = None  # type: ignore
    ProgressionEvent = DirectionEvent = ProfectionEvent = OutOfBoundsEvent = None  # type: ignore
from .fixedstars import skyfield_stars  # ENSURE-LINE
from .infrastructure.environment import collect_environment_report
from .infrastructure.environment import main as environment_report_main
from .maint import main as maint_main  # ENSURE-LINE
from .modules import (
    DEFAULT_REGISTRY,
    AstroChannel,
    AstroModule,
    AstroRegistry,
    AstroSubchannel,
    AstroSubmodule,
    bootstrap_default_registry,
)
from .modules.vca import serialize_vca_ruleset
from .narrative_overlay import (
    NarrativeOverlay,
    apply_resonance_overlay,
    format_confidence_band,
    select_resonance_focus,
)
from .profiles import (  # noqa: F401
    VCA_DOMAIN_PROFILES,
    DomainScoringProfile,
    ResonanceWeights,
    load_base_profile,
    load_profile,
    load_resonance_weights,
    load_vca_outline,
)
from .providers import (  # noqa: F401  # ENSURE-LINE
    EphemerisProvider,  # noqa: F401  # ENSURE-LINE
    get_provider,
    list_providers,
)
from .ritual import (
    CHALDEAN_ORDER,
    ELECTIONAL_WINDOWS,
    PLANETARY_DAYS,
    PLANETARY_HOUR_TABLE,
    VOID_OF_COURSE_RULES,
    ElectionalWindow,
    PlanetaryDay,
    VoidOfCourseRule,
)
from .rulesets import VCA_RULESET, get_vca_aspect, vca_orb_for
from .scoring import (
    DEFAULT_ASPECTS,
    OrbCalculator,
    OrbPolicy,
    ScoreInputs,
    ScoreResult,
    SeverityPolicy,
    VisibilityPolicy,
    compute_score,
    compute_uncertainty_confidence,
    load_dignities,
    load_orb_policy,
    load_severity_policy,
    load_visibility_policy,
    lookup_dignities,
)

__all__ = [
    "__version__",
    "ChartConfig",
    "ChartLocation",
    "NatalChart",
    "ProgressedChart",
    "ReturnChart",
    "HarmonicChart",
    "HarmonicPosition",
    "MidpointCompositeChart",
    "CompositePosition",
    "DirectedChart",
    "TransitEngine",  # ENSURE-LINE
    "TransitEngineConfig",
    "TransitEvent",  # ENSURE-LINE
    "TransitScanConfig",  # ENSURE-LINE
    "BodyPosition",
    "compute_natal_chart",
    "compute_secondary_progressed_chart",
    "compute_return_chart",
    "compute_harmonic_chart",
    "compute_composite_chart",
    "compute_solar_arc_chart",
    "DomainResolver",
    "DomainResolution",
    "ELEMENTS",
    "DOMAINS",
    "ZODIAC_ELEMENT_MAP",
    "natal_domain_factor",
    "AngleTracker",
    "body_class",
    "classify_relative_motion",
    "normalize_degrees",
    "norm360",
    "delta_angle",
    "classify_applying_separating",
    "combine_valence",
    "DomainScoringProfile",
    "VCA_DOMAIN_PROFILES",
    "ResonanceWeights",
    "compute_domain_factor",
    "rollup_domain_scores",
    "load_profile_json",
    "load_profile",
    "profile_into_ctx",
    "apply_profile_if_any",
    "load_resonance_weights",
    "NarrativeOverlay",
    "apply_resonance_overlay",
    "format_confidence_band",
    "select_resonance_focus",
    "EphemerisAdapter",
    "EphemerisConfig",
    "EphemerisSample",
    "ObserverLocation",
    "get_active_aspect_angles",
    "get_feature_flag",
    "maybe_attach_domain_fields",
    "VCA_RULESET",
    "serialize_vca_ruleset",
    "bootstrap_default_registry",
    "DEFAULT_ASPECTS",
    "DEFAULT_REGISTRY",
    "AstroRegistry",
    "AstroModule",
    "AstroSubmodule",
    "AstroChannel",
    "AstroSubchannel",
    "compute_score",
    "ScoreInputs",
    "ScoreResult",
    "OrbCalculator",
    "compute_uncertainty_confidence",
    "load_dignities",
    "lookup_dignities",
    "OrbPolicy",
    "SeverityPolicy",
    "VisibilityPolicy",
    "load_orb_policy",
    "load_severity_policy",
    "load_visibility_policy",
    "SwissEphemerisAdapter",
    "TimeScaleContext",
    "collect_environment_report",
    "environment_report_main",
    "get_vca_aspect",
    "vca_orb_for",
    "DECANS",
    "TREE_OF_LIFE_SEPHIROTH",
    "TREE_OF_LIFE_PATHS",
    "ALCHEMY_STAGES",
    "SEVEN_RAYS",
    "GOLDEN_DAWN_GRADES",
    "TAROT_MAJORS",
    "TAROT_COURTS",
    "TAROT_SPREADS",
    "NUMEROLOGY_NUMBERS",
    "MASTER_NUMBERS",
    "I_CHING_HEXAGRAMS",
    "ELDER_FUTHARK_RUNES",
    "PLANETARY_DAYS",
    "PLANETARY_HOUR_TABLE",
    "VOID_OF_COURSE_RULES",
    "ELECTIONAL_WINDOWS",
    "CHALDEAN_ORDER",
    "DecanAssignment",
    "DecanDefinition",
    "SephiraDefinition",
    "PathDefinition",
    "AlchemyStage",
    "RayDefinition",
    "GoldenDawnGrade",
    "TarotMajorArcana",
    "TarotCourtCard",
    "TarotSpread",
    "NumerologyNumber",
    "Hexagram",
    "Rune",
    "PlanetaryDay",
    "VoidOfCourseRule",
    "ElectionalWindow",
    "assign_decans",
    "decan_for_longitude",
    "VCA_CORE_BODIES",
    "VCA_EXT_ASTEROIDS",
    "VCA_CENTAURS",
    "VCA_TNOS",
    "VCA_SENSITIVE_POINTS",
    "sbdb",
    "skyfield_stars",
    "declination",
    "VALID_ZODIAC_SYSTEMS",
    "VALID_HOUSE_SYSTEMS",
    "collect_diagnostics",
    "maint_main",
    "LunationEvent",
    "EclipseEvent",
    "StationEvent",
    "ReturnEvent",
    "ProgressionEvent",
    "DirectionEvent",
    "ProfectionEvent",
    "OutOfBoundsEvent",
]

try:  # pragma: no cover - package metadata not available during tests
    __version__ = version("astroengine")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"
