apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astroengine-ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time $upstream_response_time $upstream_addr $proxy_upstream_name $upstream_status'
  limit-req-zone: '{{ .Values.controller.config["limit-req-zone"] }} zone=astroengine:10m rate=50r/s'
