apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/helm/api/templates/deployment.yaml
  - ../../infra/helm/ui/templates/deployment.yaml
patchesStrategicMerge:
  - patch.yaml
