server:
  image:
    repository: prom/prometheus
    tag: v2.43.0
  persistentVolume:
    enabled: true
    size: 50Gi
  retention: 15d
  extraFlags:
    - '--web.enable-lifecycle'
    - '--storage.tsdb.retention.time=15d'
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
