apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astroengine-api.fullname" . }}
  labels:
    {{- include "astroengine-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      {{- include "astroengine-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "astroengine-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.collectorEndpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: astroengine-api
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.rollout.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.rollout.livenessProbe | nindent 12 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
        - name: astroengine-registry
