# ======================================================================
# ASTROLOGY_RULES — Unified Ruleset (v2.18.12 FULL, Optimized)
# Deterministic unified ruleset with hybrid gating, capture margins,
# interactive prompts, symbolic track, and post-run inclusion/exclusion report.
# ======================================================================

version: "2.18.12"
ruleset_name: "ASTROLOGY_RULES_v2.18.12_FULL.yaml"
generated:
  timestamp_utc: "__AUTO__"
  seed: 271828
  author: "Astrology Project — AP-SUPER"
  notes: "Fully consolidated file (no inheritance)."

profile_defaults:
  ap_profile: "AP-SUPER"
  calc:
    house_system: "whole"
    true_node: true
    tz: "America/New_York"
    reloc: false
    sidereal: false
    stars_precessed: true
    solar_fire_timing: true
    tob_uncertainty: "est±0:45"
  source_of_truth:
    ephemeris_monthly: "Ephemeris 1900-2050 0.25 month steps.csv"
    ephemeris_hourly_optional: "ephem_hourly_2025.csv"
    individuals_csv: "ASTROLOGY_INDIVIDUALS_v*.csv"
    events_csv: "Structured_Event_Log_v*.csv"
  use_proxy_data: false
  include_usa_mundane_by_default: false

performance:
  vectorization: true
  cache_hourly_ephemeris: true
  parallel_channels: true
  gzip_intermediates: true

orbs_and_timing:
  base_orbs_deg:
    conjunction: 8.0
    opposition: 7.0
    trine: 6.0
    square: 6.0
    sextile: 4.0
    quincunx: 3.0
    minor:
      semisextile: 2.0
      semisquare: 2.0
      sesquiquadrate: 2.0
  speed_classes_deg_per_day:
    slow: ["Pluto","Neptune","Uranus","Saturn","Jupiter"]
    medium: ["Mars","Sun","Venus","Mercury"]
    fast: ["Moon"]
  timing_windows:
    slow_outer_days: 21
    medium_days: 7
    fast_moon_hours: 8
  adaptive_rules:
    widen_for_tob_uncertainty: true
    node_vertex_priority_bump: true
    eclipse_superwindow_days: 28

scoring_and_valence:
  multipliers:
    luminary: 1.10
    angularity: 1.15
    tight_orb_bonus: 1.20
    separating_penalty: 0.90
    applying_bonus: 1.05
  polarity_map:
    benefic: ["trine","sextile","conjunction (with benefics)"]
    challenging: ["square","opposition","quincunx","conjunction (with malefics)"]
  normalization:
    method: "percentile_auto_calibration"
    target_mean: 0.0
    zscore_enabled: true
    contrast_stretch:
      enabled: true
      clip_low_pct: 2.0
      clip_high_pct: 98.0

ensemble_birth_time:
  enabled: true
  samples: 9
  spread_minutes: 45
  aggregation: "mean_with_ci"

pipeline:
  stages:
    - aspect_ingest
    - rules_application
    - vectorized_smoothing
    - flashpoints
    - clustering
    - threshold_filter
    - labeling
  clustering:
    window_days: 2
    method: "windowed_grouping"
  smoothing:
    kernel: "gaussian"
    kernel_width_hours: 12
    min_samples_per_day: 24
  thresholds:
    mode: "auto_calibrated_percentiles"
    high_pos_pct: 92
    med_pos_pct: 78
    low_pos_pct: 62
    quiet_band_pct: [38, 62]
    low_neg_pct: 38
    med_neg_pct: 22
    high_neg_pct: 8

gating:
  mode: "hybrid"  # score_gate + symbolic_track
  enabled_globally: true
  consent_required: false
  heavy_channels_autogate: true

  classes:
    structural:
      min_corridor_delta: 0.06
      min_js_distance: 0.04
      min_flashpoint_delta: 0.08
      max_contribution_cap: 0.55
    dynamic:
      min_corridor_delta: 0.08
      min_js_distance: 0.05
      min_flashpoint_delta: 0.10
      max_contribution_cap: 0.45
    symbolic:
      min_corridor_delta: 0.00
      min_js_distance: 0.00
      min_flashpoint_delta: 0.00
      visibility_floor: 0.02
      weight_in_score: 0.20
      always_log_within_orb: true

  interactive:
    enabled: true
    buffers:
      corridor_delta_within: 0.02
      js_distance_within: 0.015
      flashpoint_delta_within: 0.02
    overshadowed_min_signal: 0.015
    max_candidates_per_window: 6
    on_user_confirm:
      include_and_rescore: true
      annotate_label_suffix: "(user-included near-threshold)"
      telemetry_tag: "user_inclusion"

  capture_margins:
    enabled: true
    orb_margin:
      general_extra_deg: 0.5
      vertex_extra_deg: 1.0
      weight_curve:
        exact_weight: 1.00
        at_margin_weight: 0.30
    strength_margin:
      corridor_delta_buffer: 0.015
      js_distance_buffer: 0.012
      flashpoint_delta_buffer: 0.015
      include_in_run: true
      max_weight_cap: 0.25
      annotate_label_suffix: "(capture-margin)"
      telemetry_tag: "capture_margin"
    overshadowed:
      min_signal: 0.012
      include_in_run: true
      relative_cap_vs_dominator: 0.35

  symbolic_track:
    record_all_within_orb: true
    emit_markers_on_graphs: true
    label_prefix: "Symbolic"
    include_in_flashpoint_if_coincident: true
    coincidence_hours: 12

  context_sensitivity:
    eclipse_corridor:
      expand_orb_multiplier: 1.25
      sensitivity_boost: 1.15
      window_days: 14
    vertex_policy:
      orb_weight_curve:
        tight_deg: 0.0
        tight_weight: 1.00
        loose_deg: 3.0
        loose_weight: 0.35
      min_display_weight: 0.15

  shadow_logging:
    enabled: true
    min_signal_to_log: 0.01
    attach_reason: true

channels:
  enabled_by_default:
    - self
    - eclipse_lunation
    - vertex
  auto_enabled_if_lift:
    - external
    - synastry
    - composite
    - draconic
    - harmonics_H1_to_H12
  heavy_channels:
    - network_synastry
    - composite_multi
    - declination_midpoints
    - event_log
  protections:
    include_other_individuals_only_if_user_requests: true
    exclude_usa_mundane_by_default: true

labels:
  positive:
    - "Supportive flow via {aspect}: {planetA} ↔ {planetB}"
    - "Green light window — {aspect} emphasizes {theme}"
  negative:
    - "Pressure test via {aspect}: {planetA} ↔ {planetB}"
    - "Frictions surface — {aspect} highlights {theme}"
  neutral:
    - "Quiet/neutral corridor — integration time"
  themes_map_examples:
    relationship: ["Venus","Moon","7th","DSC"]
    career: ["Saturn","MC","Sun"]
    transformation: ["Pluto","8th","ASC ruler"]

visualization:
  default_output: "text_only_interpretation"
  offer_graphs_and_csv_at_end: true
  graphs_default_off: true
  csv_default_off: true
  vizbands:
    bands:
      - name: "High Positive Intensity"
        range: ">= high_pos_pct"
      - name: "Medium Positive Intensity"
        range: "[med_pos_pct, high_pos_pct)"
      - name: "Low Positive Intensity"
        range: "[low_pos_pct, med_pos_pct)"
      - name: "Quiet/Neutral"
        range: "[quiet_low, quiet_high]"
      - name: "Low Negative Intensity"
        range: "(low_neg_pct, quiet_low)"
      - name: "Medium Negative Intensity"
        range: "(med_neg_pct, low_neg_pct]"
      - name: "High Negative Intensity"
        range: "<= high_neg_pct"
  markers:
    symbolic:
      show: true
      style: "vertical_dashed"
      opacity: 0.5
      legend: "Symbolic (Vertex/Eclipse/Stars)"
    near_threshold:
      show: true
      style: "dot"
      opacity: 0.8
      legend: "Near-threshold (tap to include)"
    capture_margin:
      show: true
      style: "triangle"
      opacity: 0.7
      legend: "Capture margin (auto-included)"
  footnotes:
    add_mean_offset_note: true
    add_gating_mode_note: "Hybrid gating with capture margins and interactive prompts; symbolic markers logged."

telemetry:
  record_corridor_delta: true
  record_js_distance: true
  record_flashpoint_delta: true
  record_channel_weights: true
  record_shadow_events: true
  record_user_inclusions: true
  record_capture_margins: true
  record_symbolic_markers: true
  record_exclusion_reasons: true
  reason_code_map:
    BELOW_THRESHOLD: "Below gating threshold"
    NEAR_THRESHOLD_BUFFER: "Near-threshold (buffer) — prompted"
    USER_DECLINED: "Prompted but user declined"
    OVERSHADOWED: "Overshadowed by stronger channel"
    OUTSIDE_ORB: "Outside adaptive orb"
    WITHIN_CAPTURE_MARGIN: "Included via capture margin"
    SYMBOLIC_ONLY: "Symbolic marker only (non-scoring)"
    INCLUDED_GATED: "Included (passed gating)"
    INCLUDED_USER: "Included by user confirmation"
    EXCLUDED_POLICY: "Excluded by policy (e.g., other-individuals not requested)"
    EXCLUDED_DUPLICATE: "Merged into composite flashpoint (duplicate)"

reporting:
  post_run_report:
    enabled: true
    sections:
      - "Summary"
      - "Included (Gated)"
      - "Included (Capture-Margin)"
      - "Included (User-Confirmed)"
      - "Symbolic Markers (Non-scoring)"
      - "Excluded (Near-Threshold)"
      - "Excluded (Below Threshold)"
      - "Excluded (Policy)"
    sort_by: ["date", "score_desc", "orb_asc"]
    fields:
      - "date"
      - "channel"
      - "aspect"
      - "entities"
      - "orb_deg"
      - "scores"
      - "reason_code"
      - "reason_text"
    output_formats:
      - "inline_table"
      - "csv_inline"
    csv_filename_pattern: "post_run_report_{start}_{end}_v{version}.csv"
    footnote: >
      Reason codes reflect gating + capture-margin logic. Symbolic markers are logged even
      when non-scoring. User-included events are annotated and rescored for this run.
      Ruleset v{version}, seed {seed}.

safety_and_fallbacks:
  graceful_degradation:
    if_missing_hourly_ephemeris: "fallback_daily_computation"
    if_missing_individual_data: "skip_and_log"
  audit_trail:
    stamp_ruleset_version: true
    stamp_seed: true
    log_gating_decisions: true

io_contract:
  outputs:
    default: ["text_interpretation", "post_run_report"]
    optional_on_request: ["graph_inline","csv_inline","graph_download","csv_download"]
    interactive_prompts: ["near_threshold_candidates"]
  behavior:
    prompt_for_graphs_at_end: true
    if_graphs_requested_display_inline_only: true
    offer_download_link_only_if_user_confirms: true
    prompt_templates:
      near_threshold_candidates: >
        The following events were near the gating threshold and were not included by default:
        {candidates}. Would you like to include any of these for this run?

compatibility:
  deterministic:
    fixed_seed: true
    float_tolerance: 1.0e-9
  metadata_stamping:
    include_version_tz_house_in_headers: true

# End of file — v2.18.12 FULL
