# ======================================================================
# ASTROLOGY_RULES — Unified Ruleset (v2.18.8 Final)
# Deterministic, optimized, and aligned with AP‑SUPER pipeline
# ======================================================================

version: "2.18.8"
ruleset_name: "ASTROLOGY_RULES_v2.18.8.yaml"
generated:
  timestamp_utc: "__AUTO__"
  seed: 271828
  author: "Astrology Project — AP‑SUPER"
  notes: "Deterministic build with gating telemetry and visualization footnotes."

profile_defaults:
  ap_profile: "AP-SUPER"
  # Global calculation flags
  calc:
    house_system: "whole"
    true_node: true
    tz: "America/New_York"
    reloc: false
    sidereal: false
    stars_precessed: true
    solar_fire_timing: true
    tob_uncertainty: "est±0:45"
  # Data sources (authoritative)
  source_of_truth:
    ephemeris_monthly: "Ephemeris 1900-2050 0.25 month steps.csv"
    ephemeris_hourly_optional: "ephem_hourly_2025.csv"
    individuals_csv: "ASTROLOGY_INDIVIDUALS_v*.csv"
    events_csv: "Structured_Event_Log_v*.csv"
    # Composite/synastry/other structured project files may be present; use only if explicitly requested by user.
  use_proxy_data: false
  include_usa_mundane_by_default: false

orbs_and_timing:
  # Adaptive orbs by planetary speed & aspect type;
  # these are nominal maxima—final orbs are auto-shrunk/expanded by speed class.
  base_orbs_deg:
    conjunction: 8.0
    opposition: 7.0
    trine: 6.0
    square: 6.0
    sextile: 4.0
    quincunx: 3.0
    minor:
      semisextile: 2.0
      semisquare: 2.0
      sesquiquadrate: 2.0
  speed_classes_deg_per_day:
    slow: ["Pluto","Neptune","Uranus","Saturn","Jupiter"]
    medium: ["Mars","Sun","Venus","Mercury"]
    fast: ["Moon"]
  timing_windows:
    # Baseline windows before adaptive adjustments
    slow_outer_days: 21
    medium_days: 7
    fast_moon_hours: 8
  adaptive_rules:
    widen_for_tob_uncertainty: true   # widens orbs & windows with a 9-sample ensemble (±45m)
    node_vertex_priority_bump: true   # eclipses & vertex get pre-flight priority bump
    eclipse_superwindow_days: 28      # for lunation/eclipse clustering and lead/lag

scoring_and_valence:
  multipliers:
    luminary: 1.10
    angularity: 1.15          # ASC/MC/IC/DSC & whole-sign 1/4/7/10 emphasis
    tight_orb_bonus: 1.20
    separating_penalty: 0.90
    applying_bonus: 1.05
  polarity_map:
    benefic: ["trine","sextile","conjunction (with benefics)"]
    challenging: ["square","opposition","quincunx","conjunction (with malefics)"]
  normalization:
    method: "percentile_auto_calibration"
    target_mean: 0.0
    zscore_enabled: true
    # Contrast-stretch option for viz profiles; preserves mean offset note in footers
    contrast_stretch:
      enabled: true
      clip_low_pct: 2.0
      clip_high_pct: 98.0

ensemble_birth_time:
  enabled: true
  samples: 9
  spread_minutes: 45
  aggregation: "mean_with_ci"   # aggregates intensity curves with confidence bounds

pipeline:
  stages:
    - aspect_ingest
    - rules_application        # adaptive orbs, timing windows, multipliers
    - vectorized_smoothing     # kernel smoothing for intensity series
    - flashpoints              # local maxima/minima tagging
    - clustering               # 2-day window grouping
    - threshold_filter         # auto-calibrated percentiles
    - labeling                 # short NL labels mapped to valence + top aspect
  clustering:
    window_days: 2
    method: "windowed_grouping"
  smoothing:
    kernel: "gaussian"
    kernel_width_hours: 12
    min_samples_per_day: 24
  thresholds:
    mode: "auto_calibrated_percentiles"
    high_pos_pct: 92
    med_pos_pct: 78
    low_pos_pct: 62
    quiet_band_pct: [38, 62]
    low_neg_pct: 38
    med_neg_pct: 22
    high_neg_pct: 8

gating:
  # Pre-flight gating compares baseline vs. "baseline + candidate channel"
  # using corridor Δ, JS distance, and flashpoint Δ. Auto-enable if meaningful lift.
  enabled_globally: true
  consent_required: false
  heavy_channels_autogate: true
  telemetry:
    record_corridor_delta: true
    record_js_distance: true
    record_flashpoint_delta: true
  criteria:
    min_corridor_delta: 0.08
    min_js_distance: 0.05
    min_flashpoint_delta: 0.10
  priority_bumps:
    eclipse_events: true
    vertex_events: true

channels:
  # AP‑SUPER computes all enabled channels, but ONLY the user’s chart for general queries.
  enabled_by_default:
    - self
    - eclipse_lunation
  auto_enabled_if_lift:
    - external
    - synastry
    - composite
    - draconic
    - harmonics_H1_to_H12
  heavy_channels:     # still pass through auto‑gating; no manual consent step during testing
    - network_synastry
    - composite_multi
    - declination_midpoints
    - event_log
  protections:
    include_other_individuals_only_if_user_requests: true
    exclude_usa_mundane_by_default: true

labels:
  # Natural language label templates mapped to valence + top aspect
  positive:
    - "Supportive flow via {aspect}: {planetA} ↔ {planetB}"
    - "Green light window — {aspect} emphasizes {theme}"
  negative:
    - "Pressure test via {aspect}: {planetA} ↔ {planetB}"
    - "Frictions surface — {aspect} highlights {theme}"
  neutral:
    - "Quiet/neutral corridor — integration time"
  themes_map_examples:
    relationship: ["Venus","Moon","7th","DSC"]
    career: ["Saturn","MC","Sun"]
    transformation: ["Pluto","8th","ASC ruler"]

visualization:
  default_output: "text_only_interpretation"
  offer_graphs_and_csv_at_end: true
  graphs_default_off: true
  csv_default_off: true
  vizbands:
    bands:
      - name: "High Positive Intensity"
        range: ">= high_pos_pct"
      - name: "Medium Positive Intensity"
        range: "[med_pos_pct, high_pos_pct)"
      - name: "Low Positive Intensity"
        range: "[low_pos_pct, med_pos_pct)"
      - name: "Quiet/Neutral"
        range: "[quiet_low, quiet_high]"
      - name: "Low Negative Intensity"
        range: "(low_neg_pct, quiet_low)"
      - name: "Medium Negative Intensity"
        range: "(med_neg_pct, low_neg_pct]"
      - name: "High Negative Intensity"
        range: "<= high_neg_pct"
  footnote_template: >
    Test: {test_type} · Calc: whole‑sign houses, true node on, precessed stars, Solar Fire timing on.
    Kernel: {kernel}/{kernel_width_hours}h · Thresholds: auto‑calibrated percentiles.
    Channels enabled: {channels_enabled} (heavy channels auto‑gated).
    Mean offset (if any) after contrast‑stretch: {mean_offset:.3f}. Ruleset v{version}, seed {seed}.

safety_and_fallbacks:
  graceful_degradation:
    if_missing_hourly_ephemeris: "fallback_daily_computation"
    if_missing_individual_data: "skip_and_log"
  audit_trail:
    stamp_ruleset_version: true
    stamp_seed: true
    log_gating_decisions: true

io_contract:
  outputs:
    default: ["text_interpretation"]
    optional_on_request: ["graph_inline","csv_inline","graph_download","csv_download"]
  behavior:
    prompt_for_graphs_at_end: true
    if_graphs_requested_display_inline_only: true
    offer_download_link_only_if_user_confirms: true

compatibility:
  deterministic:
    fixed_seed: true
    float_tolerance: 1.0e-9
  metadata_stamping:
    include_version_tz_house_in_headers: true

# End of file — v2.18.8
