
meta:
  name: ASTROLOGY_RULES
  version: 3.17
  date: 2025-08-31
  notes: >
    Optimization pass: Story Mode uses an orb *modifier* (additive/scale) instead of a separate table.
    - Keeps inclusivity high without duplicating orb specs
    - Applies after base orbs (and bonuses), then clamps to max values
    - All v3.16 features retained (channels/valence, isolation, augmentations)

defaults:
  timezone: America/New_York
  house_system: Placidus
  orb_margin_degrees: 0.5
  orb_margin_vertex: 1.0
  near_threshold_buffer: 0.015
  profiles_enabled: [AP-SUPER, AP-LIGHT, AP-STRICT, AP-COMPOSITE, AP-EXTERNAL, AP-MUNDANE]
  optimizers:
    enable_deduplicate_events: true
    collapse_minor_echoes: true
    prune_inactive_modules: true
  # Central base orb table (used by modules unless they add modifiers)
  orbs_base_deg:
    conjunction: 5
    opposition: 5
    square: 4
    trine: 4
    sextile: 3
    quincunx: 2
    semisquare: 2
    sesquiquadrate: 2
  orb_bonuses_deg:
    luminary: 1.0
    angle: 1.0
    eclipse: 1.0
    vertex: 1.0

profiles:
  AP-SUPER:
    description: Full detail capture with capture margins + gating.
    modules: [TransitsCore, Progressions, SolarArcs, Returns, Eclipses, Composites, Harmonics, Draconic, NarrativeText]
  AP-LIGHT:
    description: Quick scan.
    modules: [TransitsCore, Eclipses]
  AP-STRICT:
    description: Minimal noise.
    modules: [TransitsCore, Eclipses]
  AP-COMPOSITE:
    description: Relationship-focused.
    modules: [Composites, NarrativeText]
  AP-EXTERNAL:
    description: External triggers/events focus.
    modules: [TransitsCore, Progressions, SolarArcs, Eclipses]
  AP-MUNDANE:
    description: Collective/global focus.
    modules: [TransitsCore, Eclipses]

modules:

  TransitsCore:
    kind: transits
    enabled: true
    # Inherit defaults.orbs_base_deg; no modifier applied here

  Progressions:
    kind: secondary_progressions
    enabled: true

  SolarArcs:
    kind: solar_arcs
    enabled: true

  Returns:
    kind: returns
    enabled: true
    include:
      solar_return: true
      lunar_return: true

  Eclipses:
    kind: eclipses
    enabled: true

  Composites:
    kind: composites
    enabled: true
    pairings_default: [self_plus_remy, self_plus_jung]
    include_midpoints: true

  Harmonics:
    kind: harmonics
    enabled: true
    range: [1, 12]
    include_numbers: true

  Draconic:
    kind: draconic
    enabled: true

  NarrativeText:
    kind: narrative_text
    enabled: true

    inputs:
      include_layers:
        natal: true
        transits: true
        secondary_progressions: true
        solar_arcs: true
        returns:
          solar_return: true
          lunar_return: true
        eclipses: true
        ingresses: true
        draconic: true
        harmonics:
          range: [1, 12]
          include_numbers: true
        composites:
          pairings:
            - self_plus_remy
            - self_plus_jung
            - self_plus_other
          midpoints: true
        points:
          vertex: true
          antivertex: true
          nodes: true
          chiron: true
          angles: [ASC, MC, DSC, IC]
          lots: false

    gating:
      use_salience_gate: true
      salience_rules:
        time_window_days: 31
        min_weight: 0.35
        theme_alignment: true
        over_ocean_mode: true
      conflict_resolution:
        prefer_exact: true
        tie_breaker: [angles, luminaries, nodes, eclipses]
        overshadowing: keep_minor_as_echo

    # Story Mode orbs now = defaults.orbs_base_deg (+ bonuses) THEN apply this modifier
    orbs:
      policy: story_mode_inherit_plus_modifier
      capture_margin_deg: 0.5
      near_threshold_buffer: 0.015
      modifier:
        add_all_deg: 0.5         # widen every aspect by +0.5°
        scale_all: 1.05          # then scale by +5% (small, just to catch near-misses)
        extra_bonuses:
          luminary: 0.25         # additional +0.25° on top of defaults
          angle: 0.25
          eclipse: 0.25
          vertex: 0.25
        clamp_max_deg:
          conjunction: 7
          opposition: 7
          square: 6
          trine: 6
          sextile: 5
          quincunx: 4
          semisquare: 3
          sesquiquadrate: 3
      lock_policy: true

    isolation:
      optimization_exempt: true
      dedupe_collapse: false
      cache_strategy: narrative_local
      hot_window_autopin: true

    channels:
      default_include: true
      categories:
        - Identity
        - Relationships
        - Composite
        - Career
        - Creative
        - Body
        - Social
        - Other
      subchannels:
        Relationships: [Personal, Family, Collective]
        Career: [Work, Purpose, Public]
        Body: [Health, DailyRhythm]
        Social: [Friendship, Community, CollectiveTides]
      require_channel_weights: true
      weighting:
        Identity: 1.0
        Relationships: 0.9
        Composite: 0.9
        Creative: 0.8
        Body: 0.7
        Career: 0.5
        Social: 0.5
        Other: 0.3
      valence:
        use_valence: true
        scheme: [supportive, challenging, neutral, mixed]
        rules:
          supportive_when:
            - benefic_exact_to_luminary_or_angle
            - constructive_trines_sextiles_cluster
            - creative_harmonics_active
          challenging_when:
            - malefic_exact_to_luminary_or_angle
            - eclipse_to_luminary_or_angle
            - health_stress_markers_active
          mixed_when:
            - simultaneous_supportive_and_challenging_hits
          neutral_when:
            - no_gated_events_or_below_threshold
        apply_to_storytone: true
        propagate_to_subchannels: true

    augmentations:
      rare_events:
        eclipses:
          amplify: true
          multiplier_salience: 1.35
          multiplier_valence_intensity: 1.25
          narrative_tags: [crucible, turning_point, fated]
        vertex:
          amplify: true
          multiplier_salience: 1.20
          multiplier_valence_intensity: 1.15
          narrative_tags: [encounter, destiny_axis, crossing]
        solar_arcs_to_angles:
          amplify: true
          multiplier_salience: 1.20
          multiplier_valence_intensity: 1.10
          narrative_tags: [accelerated_growth, structural_shift]
        returns_exact:
          amplify: true
          multiplier_salience: 1.10
          multiplier_valence_intensity: 1.05
          narrative_tags: [renewal, cyclical_threshold]

    narrative:
      voice: archetypal_multi_channel
      structure:
        enforce_channel_sections: true
        weave_subchannels: true
        integrate_valence: true
      include_background_echoes: true
      suppress_raw_numbers: true
      safety:
        no_predictions: true
        no_outcomes: true
        frame_as_guidance: true

pipelines:
  - name: StoryMode_September
    module: NarrativeText
    sources:
      - ref: MASTER_Ephemeris_0000-3000_merged.csv
      - ref: 2025 Ephemeris - 1HR.xls.csv
      - ref: ASTROLOGY_INDIVIDUALS_v1.5.0_clean.csv
      - ref: Structured_Event_Log_v1.5.0_clean.csv
      - ref: Chris_ALL_MODULES_MERGED.csv
      - ref: Remy_ALL_MODULES_MERGED.csv
      - ref: Chris_&_Remy_-_Composite_ALL_MERGED.csv
      - ref: Chris_Remy_Harmonics_1-12_with_numbers.csv
      - ref: Chris_Remy_Draconic_Natal_Structured.csv
      - ref: CV_CR_Composite_Midpoints.csv
      - ref: CV_Natal_Chart.csv
    options:
      window_start: 2025-09-01
      window_end:   2025-09-30
      profile: AP-SUPER
      over_ocean_mode: true
