apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astroengine-ui.fullname" . }}
  labels:
    {{- include "astroengine-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "astroengine-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "astroengine-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1002
