apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astroengine-otel.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    receivers:
      {{- toYaml .Values.configMap.receivers | nindent 6 }}
    processors:
      {{- toYaml .Values.configMap.processors | nindent 6 }}
    exporters:
      {{- toYaml .Values.configMap.exporters | nindent 6 }}
    service:
      {{- toYaml .Values.configMap.service | nindent 6 }}
