# >>> AUTO-GEN BEGIN: ci guards v1.0
name: CI Guards (Generated-Only)
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyyaml
      - name: Validate AUTO-GEN fences
        run: python scripts/validators/validate_fences.py
      - name: Validate registry
        run: python scripts/validators/validate_registry.py
      - name: Lint
        run: python -m ruff check generated/ registry/ scripts/ || true
# >>> AUTO-GEN END: ci guards v1.0
