# >>> AUTO-GEN BEGIN: ci guards v1.1
name: CI Guards
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyyaml

      - name: Export SE_EPHE_PATH if repo ephemeris folder exists
        if: ${{ hashFiles('ephe/**') != '' }}
        run: echo "SE_EPHE_PATH=${{ github.workspace }}/ephe" >> $GITHUB_ENV

      - name: Validate AUTO-GEN fences
        run: python scripts/validators/validate_fences.py

      - name: Validate registry
        run: python scripts/validators/validate_registry.py

      - name: Lint (ruff)
        run: python -m ruff check src/ generated/ registry/ scripts/ || true

      - name: Duplicate code scan (jscpd)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run jscpd
        run: npx jscpd --min-tokens 70 --threshold 2 --reporters consoleFull --silent || true
# >>> AUTO-GEN END: ci guards v1.1
