# >>> AUTO-GEN BEGIN: ci matrix 3.11+3.12 v1.0
name: CI (3.11 & 3.12)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Configure Swiss for 3.11 only
        if: matrix.python-version == '3.11'
        run: |
          if [ -d ephe ]; then echo "SE_EPHE_PATH=${{ github.workspace }}/ephe" >> $GITHUB_ENV; fi
      - name: Test
        run: |
          if [ "${{ matrix.python-version }}" = "3.12" ]; then \
            pytest -q -m "not swiss" ; \
          else \
            pytest -q ; \
          fi
# >>> AUTO-GEN END: ci matrix 3.11+3.12 v1.0
