# >>> AUTO-GEN BEGIN: CI Workflow v1.1
name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f pyproject.toml ] || [ -f setup.py ]; then pip install -e . || true; fi
      - name: Doctor (strict)
        run: |
          python -m astroengine.diagnostics --json > diagnostics.json || true
          python -m astroengine.diagnostics --strict
          python -m astroengine.diagnostics --smoketest "2025-01-01T00:00:00Z" || true
      - name: Full maintenance gate
        run: |
          python -m astroengine.maint --full --strict
      - name: Run tests
        run: pytest -q
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-${{ matrix.python-version }}
          path: diagnostics.json
# >>> AUTO-GEN END: CI Workflow v1.1
