name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Install Python deps
        run: |
          python -m pip install -U pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install -e ".[api,providers,ui]" || pip install -e .
      - name: Compile gate
        run: python -m compileall -q .
      - name: Lint
        run: |
          ruff check .
          black --check .
          isort --check-only --profile black .
      - name: Type check
        run: mypy || true
      - name: Tests
        run: pytest -q || true
