# >>> AUTO-GEN BEGIN: CI Workflow v1.1
name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint (Ruff)
        run: ruff check --output-format=github .
      - name: Format check (Black)
        run: black --check .
  tests:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            coverage: false
          - os: ubuntu-latest
            python-version: "3.11"
            coverage: true
          - os: ubuntu-latest
            python-version: "3.12"
            coverage: false
          - os: macos-latest
            python-version: "3.10"
            coverage: false
          - os: macos-latest
            python-version: "3.11"
            coverage: false
          - os: macos-latest
            python-version: "3.12"
            coverage: false
          - os: windows-latest
            python-version: "3.10"
            coverage: false
          - os: windows-latest
            python-version: "3.11"
            coverage: false
          - os: windows-latest
            python-version: "3.12"
            coverage: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Cache Swiss ephemeris
        uses: actions/cache@v4
        with:
          path: ~/.astroengine/ephemeris
          key: ${{ runner.os }}-se-${{ hashFiles('datasets/swisseph_stub/**') }}
      - name: Prepare ephemeris path
        shell: bash
        run: |
          mkdir -p "$HOME/.astroengine/ephemeris"
          cp -a datasets/swisseph_stub/. "$HOME/.astroengine/ephemeris/" 2>/dev/null || true
          echo "SE_EPHE_PATH=$HOME/.astroengine/ephemeris" >> "$GITHUB_ENV"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f pyproject.toml ] || [ -f setup.py ]; then pip install -e . || true; fi
      - name: Doctor (strict)
        run: |
          python -m astroengine.diagnostics --json > diagnostics.json || true
          python -m astroengine.diagnostics --strict
          python -m astroengine.diagnostics --smoketest "2025-01-01T00:00:00Z" || true
      - name: Full maintenance gate
        run: |
          python -m astroengine.maint --full --strict
      - name: Run tests
        if: ${{ matrix.coverage != 'true' }}
        run: pytest -q
      - name: Run tests with coverage
        if: ${{ matrix.coverage == 'true' }}
        shell: bash
        run: |
          coverage run --source=astroengine.core.angles,astroengine.core.transit_engine,astroengine.detectors.ingresses,astroengine.timelords.dashas,astroengine.engine,astroengine.events -m pytest
          coverage xml
          coverage report --fail-under=90 --include="astroengine/core/angles.py,astroengine/core/transit_engine.py,astroengine/detectors/ingresses.py,astroengine/timelords/dashas.py,astroengine/engine.py,astroengine/events.py" --omit="generated/*"
          python scripts/check_core_coverage.py coverage.xml 0.95 astroengine/core/angles.py astroengine/core/transit_engine.py
          python -m genbadge.main coverage -i coverage.xml -o docs/badges/coverage.svg --local
          git diff --exit-code docs/badges/coverage.svg
      - name: Upload diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-${{ matrix.python-version }}
          path: diagnostics.json
      - name: Upload coverage artifacts
        if: ${{ matrix.coverage == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-${{ matrix.os }}
          path: |
            coverage.xml
            docs/badges/coverage.svg
# >>> AUTO-GEN END: CI Workflow v1.1
