name: conda-ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
      - name: Show versions
        shell: bash -el {0}
        run: |
          which python
          python -V
          pip -V
      - name: Lint
        shell: bash -el {0}
        run: ruff check .
      - name: Tests
        shell: bash -el {0}
        run: pytest -q
