name: Docs

on:
  push:
    paths:
      - 'docs-site/**'
      - 'astroengine/**'
      - 'core/**'
      - 'app/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs-site/**'
      - 'astroengine/**'
      - 'core/**'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          pip install -r docs-site/requirements.txt
      - name: Build OpenAPI
        run: python docs-site/scripts/build_openapi.py
      - name: Execute notebooks
        run: python docs-site/scripts/exec_notebooks.py --refresh-fixtures
      - name: Build MkDocs
        working-directory: docs-site
        run: mkdocs build --strict
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: relationship-docs
          path: docs-site/site
