# >>> AUTO-GEN BEGIN: perf benchmark workflow v1.0
name: Perf Benchmark (Swiss)

on:
  workflow_dispatch:
  schedule:
    - cron: "23 5 * * *"

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Set ephemeris path if present
        if: ${{ hashFiles('ephe/**') != '' }}
        run: echo "SE_EPHE_PATH=${{ github.workspace }}/ephe" >> $GITHUB_ENV
      - name: Run bench
        run: |
          python scripts/perf/bench_scan.py || true
# >>> AUTO-GEN END: perf benchmark workflow v1.0
